FROM node:latest
ARG SPONSOR
RUN echo sponsor=$SPONSOR
RUN echo TESTING_ENV=$TESTING_ENV

# Development environment
# -----------------------
# FROM node:latest
# WORKDIR /webpack

# COPY package*.json ./

# RUN npm install

# ENV NODE_ENV=development

# COPY . ./

# CMD node index.js
